### PR TITLE
mdsnippets doco proposal

### PR DESCRIPTION
**Pull request by SimonCropp**
adds https://github.com/SimonCropp/MarkdownSnippets 

@damianh i am weary to propose the addition of one of my libs to someone else projects, but figured you might find this useful? if not happy to abandon this one.

I converted half the snippets. if you like the idea i will finish the rest

### CODE REVIEW

**Comment by damianh** [comment]
Hi @SimonCropp , this looks nice! Didn't know it existed. Would be very happy to accept this. Happy to have the snippets in the test project for this PR. Also happy for you a credit to be added to bottom of the main readme. I'll leverage this in the recipies repo after.

**Comment by SimonCropp** [comment]
nor this :) https://github.com/proxykit/ProxyKit#28-typed-handlers

**Comment by SimonCropp** [comment]
ok there are a few snippets left. eg

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddProxy();
    ...
}
```

didnt convert those. thoughts?

and no need for attribution.

**Comment by SimonCropp** [comment]
a few other pointers

 * there is a dotnet tool https://github.com/SimonCropp/MarkdownSnippets#installation that can be run from WindowsExplorer https://github.com/SimonCropp/MarkdownSnippets/blob/master/src/context-menu.reg
 * there is a config file u can add to a repo that both the msbuild task and the dotnet tool will respect https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/config-file.md

**Comment by damianh** [comment]
> didnt convert those. thoughts?

Totally fine.

**Comment by SimonCropp** [comment]
i think this is done

**Comment by damianh** [comment]
Thanks for this :)

**Comment by SimonCropp** [comment]
@damianh this might interest you https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/github-action.md

**Pull request merged**
